Update the appliance documentation
owncloud/doc-index pull request #14
Opened 2017-08-10 11:20 UTC by settermjd

This:

- removes any reference to "Enterprise"
- relates to https://github.com/owncloud/documentation/issues/3287

@michaelstingl can you comment, please?

2017-08-10 11:22 UTC, michaelstingl requested changes

2017-08-10 11:22 UTC, michaelstingl commented on index.rst
> +* `ownCloud X Appliance Manual <https://doc.owncloud.org/server/10.0/admin_manual/enterprise/appliance/index.html>`_
why path `enterprise`? restructure?

2017-08-10 11:24 UTC, michaelstingl requested changes

2017-08-10 11:24 UTC, michaelstingl commented on index.rst
> +The ownCloud X Appliance is a complete virtual machine image running ownCloud X, on Ubuntu Linux.
Not Ubuntu, based on Univention Server that is based on Debian

2017-08-14 13:39 UTC, settermjd commented
This was implemented in https://github.com/owncloud/documentation/pull/3296.

2017-08-14 13:53 UTC, settermjd commented
@michaelstingl, can you review again, pls?

2017-08-14 13:57 UTC, michaelstingl approved these changes

2017-08-29 11:19 UTC, merged